{
  "modified": "2025-03-28T13:06:04Z",
  "published": "2025-03-28T13:06:04Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-2988",
  "summary": "Malicious code in pychaosvm (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pychaosvm",
        "purl": "pkg:pypi/pychaosvm"
      },
      "versions": [
        "0.0.0.1"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-01987",
        "import_time": "2025-03-31T07:07:06.294326803Z",
        "modified_time": "2025-03-28T13:06:04Z",
        "sha256": "33d2c2b8c4dd4a3e463498c5f522442c0f11613d7a1223e43ed7395277a4649b",
        "source": "reversing-labs",
        "versions": [
          "0.0.0.1"
        ]
      }
    ]
  }
}
